[package]
name = "hccr"
version = "0.1.0"
edition = "2024"
authors = ["Ben Spitz <diracdeltafunk@users.noreply.github.com>"]

[lib]
name = "hccr"
path = "src/lib.rs"

[dependencies]
bitvec = "1.0.1"
fcars = { version = "0.2.1", features = ["random"] }
either = "1.16.0"
gap-sys = { version = "0.2.4", optional = true }

[features]
groups = ["dep:gap-sys"]

[patch.crates-io]
gap-sys = { path = "../gap-sys" }
