//! The horizontal join [3] * [3] * [3] and its transfer systems.

use hccr::prelude::*;

fn main() -> hccr::Result<()> {
    let c3 = chain(3);
    let (fusion, inclusions) = Lattice::horizontal_join_with_inclusions([&c3, &c3, &c3])?;
    println!("{fusion}");

    let tr = fusion.transfer_systems();
    println!("{} transfer systems", tr.size());

    // Elements are named (factor, element); the shared ends are "bot" and "top".
    let x = fusion.id((1, 2))?;
    let t = fusion.transfer_system_generated_by([(x, fusion.top())])?;
    println!("generated by (1, 2) -> top: {t}");

    // Push a transfer system on [3] into the middle copy.
    let s = c3.transfer_system_generated_by([(1, 3)])?;
    println!("{s} pushes forward to {}", s.pushforward(&inclusions[1])?);

    // Joining k copies works the same way for any k.
    for k in 1..=4 {
        let copies = vec![c3.clone(); k];
        let count = horizontal_join(&copies)?.transfer_system_count();
        println!("[3]^*{k}: {count} transfer systems");
    }
    Ok(())
}
