//! Additive drawings from a chain decomposition of the join-irreducibles.
//!
//! Call an element `p` of a finite poset *join-irreducible* unless it is the
//! least upper bound of the elements strictly below it. (For a lattice these
//! are the usual join-irreducibles; a minimal element is join-irreducible
//! unless it is the least element.) Every element is the least upper bound of
//! the join-irreducibles below it, so `p <= q` exactly when every
//! join-irreducible below `p` is below `q`.
//!
//! Partition the join-irreducibles into chains `C_1, ..., C_k`. The elements of
//! `C_i` below `p` form an initial segment of `C_i`, so `p` is determined by
//! the counts `c_i(p) = |C_i ∩ ↓p|`, and `p <= q` exactly when
//! `c(p) <= c(q)` coordinatewise: the poset embeds in a product of `k`
//! chains. An additive drawing projects that product linearly to the plane,
//! sending a step along `C_i` to a fixed vector. Steps along the same chain
//! are drawn parallel, so for a distributive lattice every cover is parallel
//! to one of `k` directions and every cover diamond is a parallelogram.
//!
//! For the transfer systems on a chain `[n]` (a Tamari lattice) the chains are
//! canonical: the join-irreducible generated by `i -> j` lies below the one
//! generated by `k -> l` exactly when `i = k` and `j <= l`. So there is one
//! chain for each source `i`, and `c_i(T)` is the length of the longest
//! relation `i -> j` in `T`.

use super::layered::LayeredCoverGraph;
use crate::bitvec_utils::is_subset;
use crate::poset::{Edge, ElementId};
use bitvec::prelude::*;
use std::collections::HashMap;

/// A minimum chain decomposition of the join-irreducibles of a poset, and
/// the resulting chain counts of every element.
pub(super) struct IrreducibleChains {
    /// `counts[p][i]` is the number of elements of chain `i` below `p`.
    counts: Vec<Vec<usize>>,
    chain_count: usize,
}

impl IrreducibleChains {
    pub(super) fn new(size: usize, covers: &[Edge]) -> Self {
        let mut upper_covers = vec![Vec::new(); size];
        let mut lower_covers = vec![Vec::new(); size];
        for edge in covers {
            upper_covers[edge.from].push(edge.to);
            lower_covers[edge.to].push(edge.from);
        }

        // up[p] is the principal up-set of p, built in reverse topological
        // order.
        let mut pending: Vec<usize> = upper_covers.iter().map(Vec::len).collect();
        let mut ready: Vec<usize> = (0..size).filter(|&p| pending[p] == 0).collect();
        let mut up = vec![bitvec![0; size]; size];
        while let Some(p) = ready.pop() {
            up[p].set(p, true);
            for &q in &upper_covers[p] {
                let above = up[q].clone();
                up[p] |= above.as_bitslice();
            }
            for &q in &lower_covers[p] {
                pending[q] -= 1;
                if pending[q] == 0 {
                    ready.push(q);
                }
            }
        }

        // p is the least upper bound of the elements below it exactly when
        // every common upper bound of its lower covers lies above p.
        let irreducibles: Vec<usize> = (0..size)
            .filter(|&p| {
                let mut bounds = bitvec![1; size];
                for &q in &lower_covers[p] {
                    bounds &= up[q].as_bitslice();
                }
                !is_subset(&bounds, &up[p])
            })
            .collect();

        let chains = minimum_chain_cover(&irreducibles, |a, b| a != b && up[a][b]);
        let counts = (0..size)
            .map(|p| {
                chains
                    .iter()
                    .map(|chain| chain.iter().filter(|&&j| up[j][p]).count())
                    .collect()
            })
            .collect();
        Self {
            counts,
            chain_count: chains.len(),
        }
    }

    /// The number of join-irreducibles below each element, less the minimum
    /// of these numbers.
    pub(super) fn heights(&self) -> Vec<usize> {
        let heights: Vec<usize> = self.counts.iter().map(|c| c.iter().sum()).collect();
        let lowest = heights.iter().copied().min().unwrap_or(0);
        heights.into_iter().map(|height| height - lowest).collect()
    }
}

/// Partitions `elements` into as few chains as possible (Dilworth), by a
/// maximum matching between each element and an element above it. Each chain
/// is listed from the bottom.
fn minimum_chain_cover(elements: &[usize], less: impl Fn(usize, usize) -> bool) -> Vec<Vec<usize>> {
    let count = elements.len();
    let above: Vec<Vec<usize>> = (0..count)
        .map(|a| {
            (0..count)
                .filter(|&b| less(elements[a], elements[b]))
                .collect()
        })
        .collect();
    // matched_below[b] = a means a and b are consecutive in a chain.
    let mut matched_below: Vec<Option<usize>> = vec![None; count];

    fn augment(
        a: usize,
        above: &[Vec<usize>],
        matched_below: &mut [Option<usize>],
        visited: &mut [bool],
    ) -> bool {
        for &b in &above[a] {
            if visited[b] {
                continue;
            }
            visited[b] = true;
            if matched_below[b].is_none_or(|other| augment(other, above, matched_below, visited)) {
                matched_below[b] = Some(a);
                return true;
            }
        }
        false
    }
    for a in 0..count {
        augment(a, &above, &mut matched_below, &mut vec![false; count]);
    }

    let mut matched_above = vec![None; count];
    for (b, a) in matched_below.iter().enumerate() {
        if let Some(a) = *a {
            matched_above[a] = Some(b);
        }
    }
    (0..count)
        .filter(|&a| matched_below[a].is_none())
        .map(|start| {
            let mut chain = vec![elements[start]];
            let mut current = start;
            while let Some(next) = matched_above[current] {
                chain.push(elements[next]);
                current = next;
            }
            chain
        })
        .collect()
}

impl LayeredCoverGraph {
    /// Places the poset elements additively.
    ///
    /// A step along the chain given the `s`-th direction moves
    /// `s - (k - 1) / 2` units sideways, so the `k` directions are evenly
    /// spread and symmetric. Of the ways of assigning directions to chains,
    /// the one giving the fewest crossings is used. Elements at the same height
    /// that would come too close are then moved apart as little as possible
    /// (in the least-squares sense), and any lean is sheared away.
    pub(super) fn additive_coordinates(
        &self,
        chains: &IrreducibleChains,
        covers: &[Edge],
        x_spacing: f64,
        y_spacing: f64,
    ) -> HashMap<ElementId, (f64, f64)> {
        let k = chains.chain_count;
        let tie_break = self.vertex_positions();
        let place = |slots: &[usize]| {
            let directions: Vec<f64> = slots
                .iter()
                .map(|&slot| slot as f64 - (k as f64 - 1.0) / 2.0)
                .collect();
            let raw: Vec<f64> = chains
                .counts
                .iter()
                .map(|c| c.iter().zip(&directions).map(|(&n, &a)| n as f64 * a).sum())
                .collect();
            let mut x = self.separate_within_levels(&raw, &tie_break);
            self.remove_lean(&mut x);
            x
        };
        let score = |x: &[f64]| {
            let points: Vec<(f64, f64)> = (0..self.real_count)
                .map(|id| (x[id] * x_spacing, self.levels[id] as f64 * y_spacing / 2.0))
                .collect();
            drawn_defects(&points, covers, NODE_CLEARANCE * x_spacing.min(y_spacing))
        };

        // slots[i] is the direction given to chain i. A permutation and its
        // reverse give mirror-image drawings, so only one is tried.
        let mut slots: Vec<usize> = (0..k).collect();
        let mut best_x = place(&slots);
        let mut best_score = score(&best_x);
        let work = covers.len().pow(2).max(1);
        if (1..=k).product::<usize>().saturating_mul(work) <= EXHAUSTIVE_BUDGET {
            let mut candidate = slots.clone();
            while next_permutation(&mut candidate) {
                if candidate.first() > candidate.last() {
                    continue;
                }
                let x = place(&candidate);
                let candidate_score = score(&x);
                if candidate_score < best_score {
                    (best_x, best_score) = (x, candidate_score);
                }
            }
        } else {
            // Too many chains to try every assignment: swap pairs of
            // directions while that helps.
            let mut improved = true;
            while improved {
                improved = false;
                for i in 0..k {
                    for j in i + 1..k {
                        slots.swap(i, j);
                        let x = place(&slots);
                        let candidate_score = score(&x);
                        if candidate_score < best_score {
                            (best_x, best_score, improved) = (x, candidate_score, true);
                        } else {
                            slots.swap(i, j);
                        }
                    }
                }
            }
        }

        self.centered_coordinates(&best_x, x_spacing, y_spacing)
    }

    /// Moves the poset elements at each level as little as possible, in the
    /// least-squares sense, so that consecutive ones are at least one unit
    /// apart. Elements keep the order of `raw`, with ties broken by `tie_break`.
    fn separate_within_levels(&self, raw: &[f64], tie_break: &[usize]) -> Vec<f64> {
        let mut by_level: HashMap<usize, Vec<usize>> = HashMap::new();
        for id in 0..self.real_count {
            by_level.entry(self.levels[id]).or_default().push(id);
        }
        let mut x = vec![0.0; self.levels.len()];
        for mut level in by_level.into_values() {
            level.sort_by(|&a, &b| {
                raw[a]
                    .total_cmp(&raw[b])
                    .then(tie_break[a].cmp(&tie_break[b]))
                    .then(a.cmp(&b))
            });
            let targets: Vec<(f64, f64)> = level
                .iter()
                .enumerate()
                .map(|(index, &id)| (raw[id] - index as f64, 1.0))
                .collect();
            for (index, (&id, fitted)) in level
                .iter()
                .zip(super::coordinates::isotonic_fit(&targets))
                .enumerate()
            {
                x[id] = fitted + index as f64;
            }
        }
        x
    }
}

/// Above this many segment comparisons, chains are assigned directions by
/// local search instead of by trying every permutation.
const EXHAUSTIVE_BUDGET: usize = 50_000_000;

/// How close, as a fraction of the spacing, an edge may pass to a node that is
/// not one of its endpoints before it counts as passing through it.
const NODE_CLEARANCE: f64 = 0.2;

/// Counts proper crossings between drawn edges, then edges passing within
/// `clearance` of a node other than their endpoints.
fn drawn_defects(points: &[(f64, f64)], covers: &[Edge], clearance: f64) -> (usize, usize) {
    const EPSILON: f64 = 1e-9;
    let cross = |o: (f64, f64), a: (f64, f64), b: (f64, f64)| {
        (a.0 - o.0) * (b.1 - o.1) - (a.1 - o.1) * (b.0 - o.0)
    };
    let mut crossings = 0;
    for (index, first) in covers.iter().enumerate() {
        let (a, b) = (points[first.from], points[first.to]);
        for second in &covers[index + 1..] {
            if [second.from, second.to]
                .iter()
                .any(|&v| v == first.from || v == first.to)
            {
                continue;
            }
            let (c, d) = (points[second.from], points[second.to]);
            if cross(a, b, c) * cross(a, b, d) < -EPSILON
                && cross(c, d, a) * cross(c, d, b) < -EPSILON
            {
                crossings += 1;
            }
        }
    }
    let through = covers
        .iter()
        .filter(|edge| {
            let (a, b) = (points[edge.from], points[edge.to]);
            let length_squared = (b.0 - a.0).powi(2) + (b.1 - a.1).powi(2);
            points.iter().enumerate().any(|(id, &p)| {
                let along = (p.0 - a.0) * (b.0 - a.0) + (p.1 - a.1) * (b.1 - a.1);
                id != edge.from
                    && id != edge.to
                    && cross(a, b, p).abs() <= clearance * length_squared.sqrt()
                    && along > 0.0
                    && along < length_squared
            })
        })
        .count();
    (crossings, through)
}

/// Rearranges `values` into the next permutation in lexicographic order,
/// returning `false` (and leaving them sorted) after the last one.
fn next_permutation(values: &mut [usize]) -> bool {
    let Some(pivot) = values.windows(2).rposition(|pair| pair[0] < pair[1]) else {
        values.reverse();
        return false;
    };
    let successor = values
        .iter()
        .rposition(|&value| value > values[pivot])
        .expect("a larger value follows the pivot");
    values.swap(pivot, successor);
    values[pivot + 1..].reverse();
    true
}
