use crate::morphism::{PosetMap, PosetMapError};
use bitvec::prelude::*;
use std::collections::HashSet;
use std::fmt;
use std::sync::Arc;

/// The stable index of an element in a finite poset.
///
/// Element labels are not required to be unique, so public APIs identify
/// elements by index.
pub type ElementId = usize;

/// An ordered relation `from <= to` between elements of a poset.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct Edge {
    pub from: ElementId,
    pub to: ElementId,
}

impl Edge {
    pub fn new(from: ElementId, to: ElementId) -> Self {
        Self { from, to }
    }

    pub fn is_identity(self) -> bool {
        self.from == self.to
    }
}

impl From<(ElementId, ElementId)> for Edge {
    fn from((from, to): (ElementId, ElementId)) -> Self {
        Self { from, to }
    }
}

impl From<Edge> for (ElementId, ElementId) {
    fn from(edge: Edge) -> Self {
        (edge.from, edge.to)
    }
}

pub type EdgeSet = HashSet<Edge>;

/// Labels for elements of a disjoint union.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Either<A, B> {
    Left(A),
    Right(B),
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PosetError {
    RelationHeight {
        expected: usize,
        actual: usize,
    },
    RelationWidth {
        row: usize,
        expected: usize,
        actual: usize,
    },
    MissingReflexiveEdge {
        element: ElementId,
    },
    NotAntisymmetric {
        left: ElementId,
        right: ElementId,
    },
    NotTransitive {
        lower: ElementId,
        middle: ElementId,
        upper: ElementId,
    },
    EdgeOutOfBounds {
        edge: Edge,
        len: usize,
    },
}

impl fmt::Display for PosetError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            PosetError::RelationHeight { expected, actual } => {
                write!(f, "relation has {actual} rows, expected {expected}")
            }
            PosetError::RelationWidth {
                row,
                expected,
                actual,
            } => write!(
                f,
                "relation row {row} has width {actual}, expected {expected}"
            ),
            PosetError::MissingReflexiveEdge { element } => {
                write!(
                    f,
                    "relation is missing reflexive edge {element} <= {element}"
                )
            }
            PosetError::NotAntisymmetric { left, right } => {
                write!(
                    f,
                    "relation contains both {left} <= {right} and {right} <= {left}"
                )
            }
            PosetError::NotTransitive {
                lower,
                middle,
                upper,
            } => write!(
                f,
                "relation contains {lower} <= {middle} and {middle} <= {upper}, but not {lower} <= {upper}"
            ),
            PosetError::EdgeOutOfBounds { edge, len } => write!(
                f,
                "edge {} <= {} is out of bounds for a poset with {len} elements",
                edge.from, edge.to
            ),
        }
    }
}

impl std::error::Error for PosetError {}

/// A finite poset stored as a dense reachability matrix.
///
/// `relation[i][j]` is true if and only if `i <= j`. Element labels are not
/// required to be unique.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Poset<A> {
    elements: Vec<A>,
    relation: Vec<BitVec>,
}

#[derive(Debug, Clone)]
pub struct PosetCoproduct<A, B> {
    pub poset: Arc<Poset<Either<A, B>>>,
    pub left: PosetMap<A, Either<A, B>>,
    pub right: PosetMap<B, Either<A, B>>,
}

#[derive(Debug, Clone)]
pub struct PosetProduct<A, B> {
    pub poset: Arc<Poset<(A, B)>>,
    pub left_projection: PosetMap<(A, B), A>,
    pub right_projection: PosetMap<(A, B), B>,
}

impl<A> Poset<A> {
    /// Constructs the poset defined by `pred`.
    pub fn from_vec_by<F>(elements: Vec<A>, pred: F) -> Result<Self, PosetError>
    where
        F: Fn(&A, &A) -> bool,
    {
        let relation = elements
            .iter()
            .map(|a| elements.iter().map(|b| pred(a, b)).collect())
            .collect();
        Self::from_relation(elements, relation)
    }
}

impl<A: PartialOrd> Poset<A> {
    /// Constructs the poset defined by Rust's `PartialOrd` relation.
    pub fn from_vec(elements: Vec<A>) -> Result<Self, PosetError> {
        Poset::from_vec_by(elements, |a, b| a <= b)
    }
}

impl<A> Poset<A> {
    pub fn from_relation(elements: Vec<A>, relation: Vec<BitVec>) -> Result<Self, PosetError> {
        validate_relation(elements.len(), &relation)?;
        Ok(Self { elements, relation })
    }

    pub fn relabelled<B, F>(&self, f: F) -> Poset<B>
    where
        F: FnMut(&A) -> B,
    {
        Poset::from_validated(self.elements.iter().map(f).collect(), self.relation.clone())
    }

    /// Produces the poset generated by the given edges.
    ///
    /// Reflexive edges are added automatically and the transitive closure is
    /// computed before antisymmetry is checked.
    pub fn from_edges(
        elements: Vec<A>,
        edges: impl IntoIterator<Item = Edge>,
    ) -> Result<Self, PosetError> {
        let n = elements.len();
        let mut relation = vec![BitVec::repeat(false, n); n];
        for (i, row) in relation.iter_mut().enumerate() {
            row.set(i, true);
        }
        for edge in edges {
            if edge.from >= n || edge.to >= n {
                return Err(PosetError::EdgeOutOfBounds { edge, len: n });
            }
            relation[edge.from].set(edge.to, true);
        }
        transitive_closure(&mut relation);
        Self::from_relation(elements, relation)
    }

    pub(crate) fn from_validated(elements: Vec<A>, relation: Vec<BitVec>) -> Self {
        debug_assert!(validate_relation(elements.len(), &relation).is_ok());
        Self { elements, relation }
    }

    pub fn size(&self) -> usize {
        self.elements.len()
    }

    pub fn is_empty(&self) -> bool {
        self.elements.is_empty()
    }

    pub fn elements(&self) -> &[A] {
        &self.elements
    }

    pub fn element(&self, id: ElementId) -> Option<&A> {
        self.elements.get(id)
    }

    pub fn relation_matrix(&self) -> &[BitVec] {
        &self.relation
    }

    pub fn leq(&self, left: ElementId, right: ElementId) -> bool {
        self.relation[left][right]
    }

    pub fn validate(&self) -> Result<(), PosetError> {
        validate_relation(self.elements.len(), &self.relation)
    }

    pub fn bottom(&self) -> Option<ElementId> {
        self.relation
            .iter()
            .position(|row| row.count_ones() == self.elements.len())
    }

    pub fn top(&self) -> Option<ElementId> {
        self.relation
            .iter()
            .fold(BitVec::repeat(true, self.elements.len()), |acc, row| {
                acc & row
            })
            .first_one()
    }

    pub fn meet(&self, left: ElementId, right: ElementId) -> Option<ElementId> {
        if left >= self.size() || right >= self.size() {
            return None;
        }
        (0..self.size()).find(|&candidate| {
            self.leq(candidate, left)
                && self.leq(candidate, right)
                && (0..self.size()).all(|lower| {
                    !(self.leq(lower, left) && self.leq(lower, right)) || self.leq(lower, candidate)
                })
        })
    }

    pub fn join(&self, left: ElementId, right: ElementId) -> Option<ElementId> {
        if left >= self.size() || right >= self.size() {
            return None;
        }
        (0..self.size()).find(|&candidate| {
            self.leq(left, candidate)
                && self.leq(right, candidate)
                && (0..self.size()).all(|upper| {
                    !(self.leq(left, upper) && self.leq(right, upper)) || self.leq(candidate, upper)
                })
        })
    }

    pub fn is_lattice(&self) -> bool {
        !self.is_empty()
            && (0..self.size()).all(|i| {
                (0..self.size()).all(|j| self.meet(i, j).is_some() && self.join(i, j).is_some())
            })
    }

    pub fn is_total_order(&self) -> bool {
        (0..self.size()).all(|i| (i + 1..self.size()).all(|j| self.leq(i, j) || self.leq(j, i)))
    }

    pub fn all_relations_iter(&self) -> impl Iterator<Item = Edge> + '_ {
        self.relation
            .iter()
            .enumerate()
            .flat_map(|(from, row)| row.iter_ones().map(move |to| Edge { from, to }))
    }

    pub fn proper_relations_iter(&self) -> impl Iterator<Item = Edge> + '_ {
        self.all_relations_iter().filter(|edge| !edge.is_identity())
    }

    /// Returns the cover relations in the Hasse diagram.
    pub fn cover_relations(&self) -> EdgeSet {
        self.proper_relations_iter()
            .filter(|edge| {
                !(0..self.size()).any(|middle| {
                    middle != edge.from
                        && middle != edge.to
                        && self.leq(edge.from, middle)
                        && self.leq(middle, edge.to)
                })
            })
            .collect()
    }

    pub fn minimal_elements(&self) -> Vec<ElementId> {
        (0..self.size())
            .filter(|&id| (0..self.size()).all(|other| other == id || !self.leq(other, id)))
            .collect()
    }

    pub fn maximal_elements(&self) -> Vec<ElementId> {
        (0..self.size())
            .filter(|&id| (0..self.size()).all(|other| other == id || !self.leq(id, other)))
            .collect()
    }

    pub fn llc(&self, arrows: &EdgeSet) -> EdgeSet {
        self.all_relations_iter()
            .filter(|edge1| {
                edge1.is_identity()
                    || arrows.iter().all(|edge2| {
                        !self.leq(edge1.from, edge2.from)
                            || !self.leq(edge1.to, edge2.to)
                            || self.leq(edge1.to, edge2.from)
                    })
            })
            .collect()
    }

    pub fn rlc(&self, arrows: &EdgeSet) -> EdgeSet {
        self.all_relations_iter()
            .filter(|edge2| {
                edge2.is_identity()
                    || arrows.iter().all(|edge1| {
                        !self.leq(edge1.from, edge2.from)
                            || !self.leq(edge1.to, edge2.to)
                            || self.leq(edge1.to, edge2.from)
                    })
            })
            .collect()
    }

    /// Computes `class1` composed with `class2`.
    pub fn compose(&self, class1: &EdgeSet, class2: &EdgeSet) -> EdgeSet {
        let mut result = EdgeSet::new();
        for edge1 in class1 {
            for edge2 in class2 {
                if edge2.to == edge1.from {
                    result.insert(Edge::new(edge2.from, edge1.to));
                }
            }
        }
        result
    }

    pub fn composition_closed(&self, class: &EdgeSet) -> bool {
        class.iter().all(|edge1| {
            class.iter().all(|edge2| {
                edge2.to != edge1.from || class.contains(&Edge::new(edge2.from, edge1.to))
            })
        })
    }
}

impl<A: Clone, B: Clone> Poset<Either<A, B>> {
    pub fn disjoint_union(
        left: Arc<Poset<A>>,
        right: Arc<Poset<B>>,
    ) -> Result<PosetCoproduct<A, B>, PosetMapError> {
        let n = left.size();
        let m = right.size();
        let mut elements = Vec::with_capacity(n + m);
        elements.extend(left.elements().iter().cloned().map(Either::Left));
        elements.extend(right.elements().iter().cloned().map(Either::Right));

        let mut relation = vec![BitVec::repeat(false, n + m); n + m];
        for edge in left.all_relations_iter() {
            relation[edge.from].set(edge.to, true);
        }
        for edge in right.all_relations_iter() {
            relation[n + edge.from].set(n + edge.to, true);
        }

        let poset = Arc::new(Poset::from_validated(elements, relation));
        let left_map = PosetMap::new(left, Arc::clone(&poset), (0..n).collect())?;
        let right_map = PosetMap::new(right, Arc::clone(&poset), (n..n + m).collect())?;
        Ok(PosetCoproduct {
            poset,
            left: left_map,
            right: right_map,
        })
    }
}

impl<A: Clone, B: Clone> Poset<(A, B)> {
    pub fn product(
        left: Arc<Poset<A>>,
        right: Arc<Poset<B>>,
    ) -> Result<PosetProduct<A, B>, PosetMapError> {
        let n = left.size();
        let m = right.size();
        let mut elements = Vec::with_capacity(n * m);
        for a in left.elements() {
            for b in right.elements() {
                elements.push((a.clone(), b.clone()));
            }
        }

        let mut relation = vec![BitVec::repeat(false, n * m); n * m];
        for i1 in 0..n {
            for j1 in 0..m {
                for i2 in 0..n {
                    for j2 in 0..m {
                        if left.leq(i1, i2) && right.leq(j1, j2) {
                            relation[i1 * m + j1].set(i2 * m + j2, true);
                        }
                    }
                }
            }
        }

        let poset = Arc::new(Poset::from_validated(elements, relation));
        let left_projection = PosetMap::new(
            Arc::clone(&poset),
            left,
            (0..n).flat_map(|i| std::iter::repeat_n(i, m)).collect(),
        )?;
        let right_projection = PosetMap::new(
            Arc::clone(&poset),
            right,
            (0..n).flat_map(|_| 0..m).collect(),
        )?;
        Ok(PosetProduct {
            poset,
            left_projection,
            right_projection,
        })
    }
}

pub(crate) fn validate_relation(len: usize, relation: &[BitVec]) -> Result<(), PosetError> {
    if relation.len() != len {
        return Err(PosetError::RelationHeight {
            expected: len,
            actual: relation.len(),
        });
    }
    for (row, bits) in relation.iter().enumerate() {
        if bits.len() != len {
            return Err(PosetError::RelationWidth {
                row,
                expected: len,
                actual: bits.len(),
            });
        }
    }
    for (i, row) in relation.iter().enumerate() {
        if !row[i] {
            return Err(PosetError::MissingReflexiveEdge { element: i });
        }
    }
    for (i, row) in relation.iter().enumerate() {
        for (j, other_row) in relation.iter().enumerate().skip(i + 1) {
            if row[j] && other_row[i] {
                return Err(PosetError::NotAntisymmetric { left: i, right: j });
            }
        }
    }
    for i in 0..len {
        for j in 0..len {
            if relation[i][j] {
                for k in relation[j].iter_ones() {
                    if !relation[i][k] {
                        return Err(PosetError::NotTransitive {
                            lower: i,
                            middle: j,
                            upper: k,
                        });
                    }
                }
            }
        }
    }
    Ok(())
}

pub(crate) fn transitive_closure(relation: &mut [BitVec]) {
    let n = relation.len();
    for k in 0..n {
        for i in 0..n {
            if relation[i][k] {
                let row_k = relation[k].clone();
                relation[i] |= row_k;
            }
        }
    }
}
